### ISSUE TITLE
Open Diff in Beyond Compare button doesn't take into account unsaved changes

### ISSUE THREAD

**Issue by CalShucha-ScooterSoftware** [ScooterSoftware/bcompare-vscode#11]
Using the Open Diff in Beyond Compare button will only take into account the saved version of the files and not any changes that have been made to them in the editor

**Comment by ScooterAaron** [comment]
When interacting with the Timeline, a user can see diffs, and clicking the bc-diffs button will call to Beyond Compare to show the same diff.

If the file is Unsaved, the VS Code interface will show the Unsaved file vs. the selected timeline entry.
Launching BC-diff, however, will show the last saved (current local) version of the file instead vs. the selected timeline entry.
