### ISSUE TITLE
Doesnt work in Remote Development

### ISSUE THREAD

**Issue by fredericouellet-eaton** [ScooterSoftware/bcompare-vscode#14]
If try to use if to diff file on my Visual Code running on windows having Beyond compare installed 
That have a folder opened remotly using ssh extensiton. It doesnt work

I dont know if you could copy the files locally before opening beyong compare ?

**Comment by boramis** [comment]
Thank you for the bug report.  This was fixed in commit 97ff2ae4aa06f8084c349211b8664e946085ccf5 and is now released as v1.0.6.
