### ISSUE TITLE
unable launch bc4 in git graph view

### ISSUE THREAD

**Issue by Yangnaan** [ScooterSoftware/bcompare-vscode#15]
![pic](https://github.com/ScooterSoftware/bcompare-vscode/assets/26960677/bc234c5b-5fc6-43fd-b540-4a87e31d7c2a)

in git graph view, when i click a file, and then click the bc button, bc does not open.

**Comment by boramis** [comment]
Thank you for the bug report.  We've released v1.0.6 with a fix for this.
