### ISSUE TITLE
Compare unstaged changes to staged changes

### ISSUE THREAD

**Issue by PapaGreg28** [ScooterSoftware/bcompare-vscode#16]
**Scenario:**
- Make changes to a file
- Stage the changes
- Make additional changes to the same file
- Right click the unstaged changes and perform a diff

**Actual behavior:**
- All changes (staged and unstaged) are compared against the HEAD version of the file

**Requested behavior:**
- The unstaged version of the file is compared against the staged version of the file

**Notes:**
- The requested behavior is how it's implemented in other tools I've used. I personally find it very useful, I hope it's something that can be implemented.

**Comment by boramis** [comment]
Thank you for the feature request.  We've released v1.0.6 with support for this.
