### ISSUE TITLE
Left and right sides are reversed when comparing a staged file

### ISSUE THREAD

**Issue by PapaGreg28** [ScooterSoftware/bcompare-vscode#17]
**Scenario:**
- Make changes to a file
- Stage the changes
- Right click the staged file and perform a diff

**Actual behavior:**
- In beyond compare, the original file is on the **right** and the changes are on the **left**

**Requested behavior:**
- The original file should be on the **left**, and the changes on the **right**

**Notes:**
- This was unexpected behavior, it seems like a bug in my opinion.

**Comment by boramis** [comment]
Thank you for the bug report.  This was fixed in v1.0.6.
