### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by bitisuvanje** [ScooterSoftware/bcompare-vscode#23]
I couldn't find any OS requirements. Doesn't work on a Mac...

---

VS Code Extension Version: v1.0.5 
System Version: macOS 14.3.1 (23D60)
Kernel Version: Darwin 23.3.0

**Comment by boramis** [comment]
It should work on macOS, but you may need to open BC and use the Beyond Compare > Install Command Line Tools... command to enable it to launch BC correctly.  Once that's done, if you're still seeing incorrect behavior please let us know what steps you're taking and what errors you're seeing.

**Comment by bitisuvanje** [comment]
Great. Didn't check the source code of the extension and you could update the docs to state this. Works OK.
