### ISSUE TITLE
Can't point path of beyondcompare.exe

### ISSUE THREAD

**Issue by cpeng03d** [ScooterSoftware/bcompare-vscode#29]
I have a portable version of beyond compare.
Your extension can't find it, I can't find any setting to point the path to beyondcompare.exe?

**Comment by boramis** [comment]
On Windows if it can’t find it via the registry you’ll need to add your install directory to your user account’s %PATH% environment variable.

**Comment by cpeng03d** [comment]
Hi Zoe, thanks for your reply, I appreciate you reach out to solve the
problem.
Could you give some detail on how to add path system environment variables,
like what the name of the environment variable should be?
Thank you again.

**Comment by boramis** [comment]
There's a write-up on how to add a path to your environment variable here:
https://windowsloop.com/how-to-add-to-windows-path/

You'll need to add your BC install directory.  For a normal install that's "C:\Program Files\Beyond Compare 5", but it'll be wherever you have your portable install.  Don't include the bcompare.exe at the end.
