### ISSUE TITLE
Could not install extension 

### ISSUE THREAD

**Issue by MergeWords** [ScooterSoftware/bcompare-vscode#5]
When I try to install the extension from the extension manager or manually from the downloaded vsix file I receive the following error message: 

"Unable to install extension 'scootersoftware.bcompare-vscode' as it is not compatible with VS Code '1.82.2'."

I installed other extensions today from the extension manager without any issues.

**Comment by nagromc** [comment]
According to the [manifest](https://github.com/ScooterSoftware/bcompare-vscode/blob/72559aac9b55658fc03feadfa39dfc98b8a9c60a/package.json#L32), the extension is compatible with VS Code from v1.83.0. Try to update your VS Code installation with the latest release (v1.85.1).

**Comment by ScooterAaron** [comment]
Looks like @nagromc figured this one out. Thanks for including your version info, @MergeWords 

Closing for now, but if updating VS Code did not help, please let us know.
