### ISSUE TITLE
Beyond Compare’s _Compare Selected Files_ and VS Code’s _Compare Selected_ are misleading

### ISSUE THREAD

**Issue by nagromc** [ScooterSoftware/bcompare-vscode#6]
When selecting two files in the VS Code Explorer, I have two options to compare files: Beyond Compare’s _Compare Selected Files_ and VS Code’s _Compare Selected_.

![image](https://github.com/ScooterSoftware/bcompare-vscode/assets/752443/3b12d3e3-0e56-4b4e-b0c3-273a5e38ec4b)

It is not clear which will be invoked.

A possible solution would be:
* to replace the label _Compare Selected Files_ with:
  * _Compare Selected Files with Beyond Compare_
  * _Compare Selected Files (Beyond Compare)_
* or to group it with the _Launch Beyond Compare_ option just under in a sub-menu.

**Comment by boramis** [comment]
We just released v1.0.2 and the commands are generally under a "Beyond Compare" submenu, so it should be less confusing.
