### ISSUE TITLE
[Suggestion] Compare files across multiple vscode instances

### ISSUE THREAD

**Issue by jBrizzle** [ScooterSoftware/bcompare-vscode#7]
I'm not sure if it would be possible, but it would be great to be able to compare two files from two separate instances of Visual Studio Code.

The use case I'm thinking of is:
VS Code #1: Select file A as left file for compare
VS Code #2: Compare file B to file A from the separate instance

**Comment by boramis** [comment]
We've released v1.0.2 with support for comparing across instances.
